global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'goa-trip-app'
    static_configs:
      - targets: ['app:5000']
        labels:
          service: 'goa-holiday-packages'
          environment: 'production'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'container-metrics'
          environment: 'production'
